FROM node:20-alpine AS base

ENV NODE_ENV=development
WORKDIR /app

RUN apk add --no-cache openssl bash libc6-compat

COPY package*.json tsconfig*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "migrate:start:dev"]
