services:
  database:
    image: postgres:17.6-alpine3.22
    restart: always
    env_file:
      - ../.env.docker
    ports:
      - '5434:5432'

  app:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    ports:
      - '3500:3500'
    env_file:
      - ../.env.docker
    develop:
      watch:
        - action: sync
          path: ../src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - database
